/**
 * Recipient Entity
 * Schema definition for saved payment recipients
 * Allows users to save frequent recipients for quick payments
 */

import { randomBytes } from 'crypto';

/**
 * @enum {string}
 */
export const PaymentMethod = {
  UPI_ID: 'upi_id',
  MOBILE_NUMBER: 'mobile_number'
};

/**
 * @enum {string}
 */
export const RecipientCategory = {
  FAMILY: 'family',
  FRIENDS: 'friends',
  BILLS: 'bills',
  BUSINESS: 'business',
  OTHER: 'other'
};

/**
 * Recipient Schema Definition
 * @typedef {Object} Recipient
 * @property {string} id - Auto-generated by Base44/MongoDB
 * @property {string} name - Recipient full name
 * @property {PaymentMethod} payment_method - 'upi_id' or 'mobile_number'
 * @property {string} [upi_id] - UPI ID (if payment_method === 'upi_id')
 * @property {string} [mobile_number] - Mobile number (if payment_method === 'mobile_number')
 * @property {string} nickname - User-defined nickname (e.g., "Mom", "Rent", "Electricity")
 * @property {RecipientCategory} [category] - Category for organization
 * @property {number} [last_amount] - Last paid amount (optional convenience)
 * @property {Date} last_used - Last payment date
 * @property {number} usage_count - Number of times paid
 * @property {Date} created_date - Auto-field
 * @property {Date} updated_date - Auto-field
 * @property {string} created_by - User ID
 */

/**
 * Validates recipient data against schema
 * @param {Object} recipient - Recipient data to validate
 * @returns {{ valid: boolean, errors: string[] }}
 */
export function validateRecipient(recipient) {
  const errors = [];

  // Validate name
  if (!recipient.name || typeof recipient.name !== 'string') {
    errors.push('Recipient name is required');
  } else if (recipient.name.trim().length < 2) {
    errors.push('Recipient name must be at least 2 characters');
  }

  // Validate payment_method
  if (!recipient.payment_method) {
    errors.push('Payment method is required');
  } else if (!Object.values(PaymentMethod).includes(recipient.payment_method)) {
    errors.push('Payment method must be either "upi_id" or "mobile_number"');
  }

  // Validate conditional fields
  if (recipient.payment_method === 'upi_id') {
    if (!recipient.upi_id || typeof recipient.upi_id !== 'string') {
      errors.push('UPI ID is required when payment_method is "upi_id"');
    } else if (!isValidUPI(recipient.upi_id)) {
      errors.push('Invalid UPI ID format');
    }
  }

  if (recipient.payment_method === 'mobile_number') {
    if (!recipient.mobile_number || typeof recipient.mobile_number !== 'string') {
      errors.push('Mobile number is required when payment_method is "mobile_number"');
    } else if (!isValidMobileNumber(recipient.mobile_number)) {
      errors.push('Invalid mobile number format (must be 10-digit Indian number)');
    }
  }

  // Validate nickname
  if (!recipient.nickname || typeof recipient.nickname !== 'string') {
    errors.push('Nickname is required');
  } else if (recipient.nickname.trim().length < 2) {
    errors.push('Nickname must be at least 2 characters');
  }

  // Validate category if provided
  if (recipient.category && !Object.values(RecipientCategory).includes(recipient.category)) {
    errors.push('Invalid category');
  }

  // Validate last_amount if provided
  if (recipient.last_amount !== undefined && recipient.last_amount !== null) {
    if (typeof recipient.last_amount !== 'number' || recipient.last_amount <= 0) {
      errors.push('Last amount must be a positive number');
    }
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Generates a unique recipient ID
 * @returns {string}
 */
export function generateRecipientId() {
  const timestamp = Date.now().toString(36);
  const random = randomBytes(4).toString('hex');
  return `RCP${timestamp}${random}`.toUpperCase();
}

/**
 * Creates a recipient object with defaults
 * @param {Object} data - Recipient data
 * @returns {Recipient}
 */
export function createRecipient(data) {
  return {
    name: data.name,
    payment_method: data.payment_method,
    upi_id: data.payment_method === 'upi_id' ? data.upi_id : undefined,
    mobile_number: data.payment_method === 'mobile_number' ? data.mobile_number : undefined,
    nickname: data.nickname,
    category: data.category || RecipientCategory.OTHER,
    last_amount: data.last_amount || null,
    last_used: new Date(),
    usage_count: 0,
    recipient_id: generateRecipientId()
    // id, created_date, updated_date, created_by will be set by database
  };
}

/**
 * Validates UPI ID format
 * @param {string} upiId - UPI ID to validate
 * @returns {boolean}
 */
function isValidUPI(upiId) {
  const upiRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+$/;
  return upiRegex.test(upiId);
}

/**
 * Validates Indian mobile number
 * @param {string} mobile - Mobile number to validate
 * @returns {boolean}
 */
function isValidMobileNumber(mobile) {
  const cleaned = mobile.replace(/[\s-]/g, '');
  const mobileRegex = /^[6-9]\d{9}$/;
  return mobileRegex.test(cleaned);
}

/**
 * Sanitizes recipient data for safe storage
 * @param {Recipient} recipient - Recipient to sanitize
 * @returns {Recipient}
 */
export function sanitizeRecipient(recipient) {
  return {
    ...recipient,
    name: recipient.name?.trim(),
    nickname: recipient.nickname?.trim(),
    upi_id: recipient.upi_id?.toLowerCase().trim(),
    mobile_number: recipient.mobile_number?.replace(/[\s-]/g, ''),
    category: recipient.category || RecipientCategory.OTHER
  };
}

/**
 * Updates recipient usage statistics
 * @param {Recipient} recipient - Existing recipient
 * @param {number} [amount] - Optional amount paid
 * @returns {Recipient} Updated recipient
 */
export function updateRecipientUsage(recipient, amount) {
  return {
    ...recipient,
    last_used: new Date(),
    usage_count: (recipient.usage_count || 0) + 1,
    last_amount: amount || recipient.last_amount
  };
}

export default {
  PaymentMethod,
  RecipientCategory,
  validateRecipient,
  generateRecipientId,
  createRecipient,
  sanitizeRecipient,
  updateRecipientUsage
};
