/**
 * Transaction Entity
 * Schema definition for payment transactions
 * RBI-regulated payment flow compliant
 */

import { randomBytes } from 'crypto';

/**
 * @enum {string}
 */
export const PaymentMethod = {
  UPI_ID: 'upi_id',
  MOBILE_NUMBER: 'mobile_number'
};

/**
 * @enum {string}
 */
export const TransactionStatus = {
  PENDING: 'pending',
  SUCCESS: 'success',
  FAILED: 'failed'
};

/**
 * Transaction Schema Definition
 * @typedef {Object} Transaction
 * @property {string} id - Auto-generated by Base44
 * @property {PaymentMethod} payment_method - ⭐required: 'upi_id' or 'mobile_number'
 * @property {string} [upi_id] - Conditional (required if payment_method === 'upi_id')
 * @property {string} [mobile_number] - Conditional (required if payment_method === 'mobile_number')
 * @property {string} recipient_name - Recipient full name
 * @property {number} amount - Amount in INR (⭐required)
 * @property {string} [note] - Optional transaction note
 * @property {TransactionStatus} status - ⭐required, default: 'pending'
 * @property {string} transaction_id - Unique reference ID
 * @property {Date} created_date - Auto-field (Base44)
 * @property {Date} updated_date - Auto-field (Base44)
 * @property {string} created_by - Auto-field (Base44)
 */

/**
 * Validates transaction data against schema
 * @param {Object} transaction - Transaction data to validate
 * @returns {{ valid: boolean, errors: string[] }}
 */
export function validateTransaction(transaction) {
  const errors = [];

  // Validate payment_method (⭐required)
  if (!transaction.payment_method) {
    errors.push('payment_method is required');
  } else if (!Object.values(PaymentMethod).includes(transaction.payment_method)) {
    errors.push('payment_method must be either "upi_id" or "mobile_number"');
  }

  // Validate conditional fields
  if (transaction.payment_method === 'upi_id') {
    if (!transaction.upi_id || typeof transaction.upi_id !== 'string') {
      errors.push('upi_id is required when payment_method is "upi_id"');
    } else if (!isValidUPI(transaction.upi_id)) {
      errors.push('Invalid UPI ID format');
    }
  }

  if (transaction.payment_method === 'mobile_number') {
    if (!transaction.mobile_number || typeof transaction.mobile_number !== 'string') {
      errors.push('mobile_number is required when payment_method is "mobile_number"');
    } else if (!isValidMobileNumber(transaction.mobile_number)) {
      errors.push('Invalid mobile number format (must be 10-digit Indian number)');
    }
  }

  // Validate amount (⭐required)
  if (transaction.amount === undefined || transaction.amount === null) {
    errors.push('amount is required');
  } else if (typeof transaction.amount !== 'number' || transaction.amount <= 0) {
    errors.push('amount must be a positive number');
  }

  // Validate recipient_name
  if (!transaction.recipient_name || typeof transaction.recipient_name !== 'string') {
    errors.push('recipient_name is required');
  } else if (transaction.recipient_name.trim().length < 2) {
    errors.push('recipient_name must be at least 2 characters');
  }

  // Validate status if provided
  if (transaction.status && !Object.values(TransactionStatus).includes(transaction.status)) {
    errors.push('status must be one of: pending, success, failed');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Generates a unique transaction ID
 * @returns {string}
 */
export function generateTransactionId() {
  const timestamp = Date.now().toString(36);
  const random = randomBytes(8).toString('hex');
  return `TXN${timestamp}${random}`.toUpperCase();
}

/**
 * Creates a transaction object with defaults
 * @param {Object} data - Transaction data
 * @returns {Transaction}
 */
export function createTransaction(data) {
  return {
    payment_method: data.payment_method,
    upi_id: data.payment_method === 'upi_id' ? data.upi_id : undefined,
    mobile_number: data.payment_method === 'mobile_number' ? data.mobile_number : undefined,
    recipient_name: data.recipient_name,
    amount: data.amount,
    note: data.note || '',
    status: data.status || TransactionStatus.PENDING,
    transaction_id: generateTransactionId()
    // id, created_date, updated_date, created_by will be set by Base44
  };
}

/**
 * Validates UPI ID format
 * @param {string} upiId - UPI ID to validate
 * @returns {boolean}
 */
function isValidUPI(upiId) {
  // Basic UPI format: identifier@bank
  const upiRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+$/;
  return upiRegex.test(upiId);
}

/**
 * Validates Indian mobile number
 * @param {string} mobile - Mobile number to validate
 * @returns {boolean}
 */
function isValidMobileNumber(mobile) {
  // Remove spaces and dashes
  const cleaned = mobile.replace(/[\s-]/g, '');
  // Check for 10-digit Indian number starting with 6-9
  const mobileRegex = /^[6-9]\d{9}$/;
  return mobileRegex.test(cleaned);
}

/**
 * Sanitizes transaction data for safe storage
 * @param {Transaction} transaction - Transaction to sanitize
 * @returns {Transaction}
 */
export function sanitizeTransaction(transaction) {
  return {
    ...transaction,
    recipient_name: transaction.recipient_name?.trim(),
    note: transaction.note?.trim() || '',
    upi_id: transaction.upi_id?.toLowerCase().trim(),
    mobile_number: transaction.mobile_number?.replace(/[\s-]/g, '')
  };
}

export default {
  PaymentMethod,
  TransactionStatus,
  validateTransaction,
  generateTransactionId,
  createTransaction,
  sanitizeTransaction
};
